### PR TITLE
Move COFOG to the standard itemClassificationScheme codelist

### PR DESCRIPTION
**Pull request by ColinMaudry**
https://github.com/open-contracting/standard/issues/1157

### CODE REVIEW

**Review by jpmckinney — APPROVED** [review]

**Comment by ColinMaudry** [comment]
@jpmckinney I don't have enough rights to access Settings and change the main branch on this repo.

**Comment by jpmckinney** [comment]
@ColinMaudry All extensions should remain on "master" because too much code depends on that being the case.

**Comment by ColinMaudry** [comment]
@jpmckinney What about https://github.com/open-contracting-extensions/ocds_legalBasis_extension/pull/6#issuecomment-778516885 ?

My understanding was that Github redirected automatically to main branch (1.1 or 1.2) when an unknown branch is requested (master).

**Comment by ColinMaudry** [comment]
This redirection doesn't seem to work:

https://raw.githubusercontent.com/open-contracting-extensions/ocds_legalBasis_extension/bla/extension.json would redirect to https://raw.githubusercontent.com/open-contracting-extensions/ocds_legalBasis_extension/1.1/extension.json, but it returns a 404.

**Comment by jpmckinney** [comment]
I think maybe it only works for deleted branches: https://raw.githubusercontent.com/open-contracting-extensions/ocds_legalBasis_extension/master/extension.json

**Comment by jpmckinney** [comment]
> @jpmckinney What about [open-contracting-extensions/ocds_legalBasis_extension#6 (comment)](https://github.com/open-contracting-extensions/ocds_legalBasis_extension/pull/6#issuecomment-778516885) ?

Making an exception (master -> 1.1) is less work than changing a default (master -> main). It's certainly possible to change the default, but it will affect a lot more code that has logic around the name of the default (beyond just requesting the URL).

In short, all code would need to support two possible default values. Since more extensions might move toward the 1.1/1.2 pattern, I'd rather wait to see if that's actually the better new default.

**Comment by jpmckinney** [comment]
I've reconfigured this repository's branches.

**Pull request merged**
