### PR TITLE
Schema, extension meta, README with example

### PR DESCRIPTION
**Pull request by ColinMaudry**

### CODE REVIEW

**Comment by ColinMaudry** [comment]
Hi @jpmckinney,

I'm getting the following errors, and I can't figure out how to fix them.

```
ERROR: release-schema.json array should be `wholeListMerge` instead of nullable at /definitions/Organization/properties/details/properties/classifications
```

In OCDS some arrays are nullable, some aren't. I'm not sure what the rule is in that respect. I see that most arrays are nullable and they don't have a special merging property.

**Comment by ColinMaudry** [comment]
```
test_json.py::test_json_schema
release-schema.json has deep properties at /definitions/Organization/properties/details
```

Here I think the check doesn't like that I modify the Organization object while I'm actually interested in a sub-object, `details`. I haven't found another schema where a sub-object is extended.

**Comment by jpmckinney** [comment]
Only the first one is an error; the second one is a warning.

In OCDS, only string arrays should be nullable; object arrays shouldn't be nullable.

For organization classifications, I think the merge behavior needs to be `wholeListMerge` (i.e. the publisher needs to provide all classifications, every time).

**Comment by ColinMaudry** [comment]
```
test_json.py::test_json_merge_patch
 ERROR: release-schema.json object array should require `id` property at /definitions/Classification (from /properties/parties/items/properties/details/properties/classifications
```

```
test_json.py::test_json_merge_patch
ERROR: release-schema.json object array should require `id` property at /definitions/Classification (from /definitions/Organization/properties/details/properties/classificatio
```

Classification has an id. I don't get it.

**Comment by jpmckinney** [comment]
Set `"wholeListMerge": true` after uniqueItems – it will fix everything :)

**Comment by ColinMaudry** [comment]
`test_readme.py` fails because it doesn't find the `ocdskit` module.

```
ImportError while importing test module '/tmp/test_readme.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/tmp/test_readme.py:15: in <module>
    from ocdskit.schema import get_schema_fields
E   ModuleNotFoundError: No module named 'ocdskit'
```

I wonder if this is caused by this change of yours: https://github.com/open-contracting/standard-maintenance-scripts/commit/39a0111594cbeb736a626812cfeef39ed190a31e#diff-212a75168b89d5b9e3d809218bf412ebR15

**Comment by jpmckinney** [comment]
I think I fixed it now, by adding ocdskit to install.sh in that repo.

**Comment by ColinMaudry** [comment]
Pfew I got it to work! :tada: . I have setup the test scripts locally, this way I won't need to push to check the extension.

**Pull request merged**
